apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
        - cartservice-deployment/cartservice.yml
patches:
        - path: cartservice.patch.yml

configMapGenerator:
        - name: cm2
          literals:
            - redis_port=redis-cart:6379

