apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
        - 
patches:
        - path: adservice-deployment/adservice.patch.yml

configMapGenerator:
        - name: cm1
          literals:
            - container_port=9555

